import {
  LayoutDashboard,
  Users,
  Package,
  FolderTree,
  ShoppingBag,
  Tags,
  Star,
  Settings,
  Store,
} from "lucide-react";
import ROUTES, { DASHBOARDROUTES } from "./routes";

export const DashboardLinks = [
  {
    icon: LayoutDashboard,
    route: DASHBOARDROUTES.HOME,
    label: "Overview",
  },
  {
    icon: Store,
    route: ROUTES.HOME,
    label: "Store view",
  },
  {
    icon: ShoppingBag,
    route: DASHBOARDROUTES.ORDERS,
    label: "Orders",
  },
  {
    icon: Package,
    route: DASHBOARDROUTES.PRODUCTS,
    label: "Products",
  },
  {
    icon: FolderTree,
    route: DASHBOARDROUTES.CATEGORYS,
    label: "Categories",
  },
  {
    icon: Users,
    route: DASHBOARDROUTES.USERS,
    label: "Users",
  },
  {
    icon: Tags,
    route: DASHBOARDROUTES.PROMOCODES,
    label: "promocodes",
  },
  {
    icon: Star,
    route: DASHBOARDROUTES.REVIEWS,
    label: "reviews",
  },
  {
    icon: Settings,
    route: DASHBOARDROUTES.SETTINGS,
    label: "Settings",
  },
];

export const sizes = [
  { value: "2months", label: "2 Months" },
  { value: "4months", label: "4 Months" },
  { value: "6months", label: "6 Months" },
  { value: "8months", label: "8 Months" },
  { value: "10months", label: "10 Months" },
  { value: "12months", label: "12 Months" },
  { value: "2years", label: "2 Years" },
  { value: "4years", label: "4 Years" },
  { value: "6years", label: "6 Years" },
  { value: "8years", label: "8 Years" },
  { value: "10years", label: "10 Years" },
  { value: "12years", label: "12 Years" },
  { value: "2xs", label: "2XS" },
  { value: "xs", label: "XS" },
  { value: "s", label: "S" },
  { value: "m", label: "M" },
  { value: "l", label: "L" },
  { value: "xl", label: "XL" },
  { value: "xxl", label: "XXL" },
  { value: "3xl", label: "3XL" },
  { value: "4xl", label: "4XL" },
  { value: "5xl", label: "5XL" },
  { value: "6xl", label: "6XL" },
];

export const colors = [
  { value: "black", label: "Black", hex: "#000000" },
  { value: "white", label: "White", hex: "#FFFFFF" },
  { value: "navy", label: "Navy", hex: "#001F3F" },
  { value: "blue", label: "Blue", hex: "#3B82F6" },
  { value: "silver", label: "Silver", hex: "#C0C0C0" },
  { value: "babyblue", label: "Baby Blue", hex: "#89CFF0" },
  { value: "mintgreen", label: "Mint Green", hex: "#98FF98" },
  { value: "petrol", label: "Petrol", hex: "#005F73" },
  { value: "burgundy", label: "Burgundy", hex: "#800020" },
  { value: "green", label: "Green", hex: "#22C55E" },
  { value: "havanabrown", label: "Havana Brown", hex: "#6B4423" },
  { value: "beige", label: "Beige", hex: "#F5F5DC" },
  { value: "pink", label: "Pink", hex: "#EC4899" },
  { value: "snowwhite", label: "Snow White", hex: "#FFFAFA" },
  { value: "olivegreen", label: "Olive Green", hex: "#556B2F" },
  { value: "grey", label: "Grey", hex: "#6B7280" },
  { value: "red", label: "Red", hex: "#DC2626" },

  // Dual-color approximations
  { value: "white_black", label: "White & Black", hex: "#808080" },
  { value: "white_grey", label: "White & Gray", hex: "#C0C0C0" },
  { value: "black_grey", label: "Black & Gray", hex: "#404040" },
  { value: "black_blue", label: "Black & Blue", hex: "#000080" },
  { value: "white_blue", label: "White & Blue", hex: "#7F7FFF" },
  { value: "black_beige", label: "Black & Beige", hex: "#7A7A5E" },
  { value: "white_beige", label: "White & Beige", hex: "#FAFAE6" },
  { value: "black_red", label: "Black & Red", hex: "#800000" },
  { value: "white_red", label: "White & Red", hex: "#FF8080" },
  { value: "black_green", label: "Black & Green", hex: "#004000" },
  { value: "white_green", label: "White & Green", hex: "#80FF80" },
  { value: "black_pink", label: "Black & Pink", hex: "#7F6065" },
  { value: "white_pink", label: "White & Pink", hex: "#FFBFD9" },
  { value: "black_gold", label: "Black & Gold", hex: "#7F6B00" },
  { value: "white_gold", label: "White & Gold", hex: "#FFFFB3" },
  { value: "black_mintgreen", label: "Black & Mint Green", hex: "#4CFF4C" },
  { value: "white_mintgreen", label: "White & Mint Green", hex: "#CFFF CFFF" },
];
