import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { getWishlistIds } from "@/lib/server actions/wishlist.action";
import { WishlistInitializer } from "@/components/Initializers/WishlistInitializer";
import { getCartState } from "@/lib/server actions/cart.action";
import { CartInitializer } from "@/components/Initializers/CartInitializer";
import { CartItemStore } from "@/stores/useCartStore";
import { SessionProvider } from "next-auth/react";

const Inter = localFont({
  src: "../public/fonts/interVF.ttf",
  variable: "--font-inter",
  weight: "100 to 900",
});
const SpaceGrotesk = localFont({
  src: "../public/fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user.id;
  let wishlistIds: string[] = [];
  let cartItems: CartItemStore[] = [];
  if (userId) {
    const [{ data }, result] = await Promise.all([
      getWishlistIds(userId),
      getCartState(session.user.id),
    ]);
    console.log("result", result);

    if (result.success && result.data) cartItems = result.data.cartItems;
    if (data) wishlistIds = data;
  }

  return (
    <html lang="en">
      <body
        className={`${Inter.className} ${SpaceGrotesk.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <CartInitializer cartItems={cartItems} />
          <WishlistInitializer wishlistIds={wishlistIds} />
          <Toaster position="top-right" richColors />
          <main>{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
