import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Toaster } from "sonner";
import { auth } from "@/auth";
import { getWishlistIds } from "@/lib/server actions/wishlist.action";
import { WishlistInitializer } from "@/components/Initializers/WishlistInitializer";

const Inter = localFont({
  src: "../public/fonts/interVF.ttf",
  variable: "--font-inter",
  weight: "100 to 900",
});
const SpaceGrotesk = localFont({
  src: "../public/fonts/SpaceGroteskVF.ttf",
  variable: "--font-space-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user.id;
  let wishlistIds: string[] = [];
  if (userId) {
    const { data } = await getWishlistIds(userId);
    if (data) wishlistIds = data;
  }

  return (
    <html lang="en">
      <body
        className={`${Inter.className} ${SpaceGrotesk.variable} antialiased`}
      >
        <WishlistInitializer wishlistIds={wishlistIds} />
        <Toaster position="top-right" richColors />
        <main>{children}</main>
      </body>
    </html>
  );
}
